### ISSUE TITLE
[Bug] mod asks for ZScript v4.4.2, which is not recognized by dev-build of GZD 4.5pre

### ISSUE THREAD

**Issue by physixcat** [mmaulwurff/autoautosave#15]
I have noticed that `zscript.zc` now requires version 4.4.2, however this leads to my dev-build of GZD complaining that it only supports up to 4.4.0 (even though it's from the current GZDoom master 4.5 pre-release commit), and quitting out immediately after launch.

This is easily fixed by reverting the required version to 4.4.0 in my local copy of `zscript.zc`, but I just thought I'd report it

**Comment by mmaulwurff** [comment]
Thanks for reporting and for keeping an eye on this project!

I'm not sure what to do with this issue. I don't want to lower GZDoom version requirement because I want to encourage upgrading to 4.4.2: it contains important fixes. Probably it's worth reporting to GZDoom dev team that master branch doesn't allow 4.4.2 mods (which is odd).

Also, using master branch of Autoautosave is not recommended. It's under development and is currently unstable.
